//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkinglotOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingLotDetail
    {
        public int BLDId { get; set; }
        public string HostID { get; set; }
        public string LotID { get; set; }
        public int BookingLotID { get; set; }
        public Nullable<double> UnitPrice { get; set; }
        public Nullable<int> status { get; set; }
        public string FormatPrice
        {
            get
            {
                if (UnitPrice > 1000)
                {
                    return String.Format("{0:n}", UnitPrice);
                }
                return UnitPrice + "";
            }
        }
        public virtual BookingLot BookingLot { get; set; }
        public virtual Host Host { get; set; }
        public virtual LotHost LotHost { get; set; }
    }
}
