//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkinglotOnline.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ParkingLotOnlineEntities : DbContext
    {
        public ParkingLotOnlineEntities()
            : base("name=ParkingLotOnlineEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<BookingLot> BookingLots { get; set; }
        public virtual DbSet<BookingLotDetail> BookingLotDetails { get; set; }
        public virtual DbSet<BookingStatu> BookingStatus { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<County> Counties { get; set; }
        public virtual DbSet<Driver> Drivers { get; set; }
        public virtual DbSet<Host> Hosts { get; set; }
        public virtual DbSet<Lot> Lots { get; set; }
        public virtual DbSet<LotHost> LotHosts { get; set; }
    }
}
